<div style="width:940px;">
	<div style="width:500px;padding:20px;text-align:center;margin:0;margin-left:auto;margin-right:auto;margin-top:50px;margin-bottom:50px;border-radius:10px;background:#008FCA;">
		<div style="font-size:1.5em;font-weight:bold;margin-bottom:10px;">
			Merci d'envoyer votre chèque à l'adresse suivante pour valider votre inscription<br><br>
			ZIMMER DENTAL<br>
			2 PLACE GUSTAVE EIFFEL<br>
			BP 40237<br>
			94528 RUNGIS CEDEX
		</div>
		<a style="font-size:1.2em;color:white;" href="<?php echo $this->url; ?>">Retour</a>
	</div>
</div>