<body style="max-width: 640px;">
	<p>Bonjour,</p>

	<p>
		Nous vous remercions pour votre demande d’inscription à la <strong>Journée
		Internationale d’Implantologie Zimmer Dental</strong> qui aura lieu à Paris <strong>le
		jeudi 4 avril 2013.</strong> 
		<br />
		Votre paiement a bien été pris en compte. Un courrier de <strong>confirmation</strong> ainsi qu’une facture acquittée vous parviendront prochainement.
		<br />
		Dans l’attente de vous accueillir à l’Institut Pasteur,
	</p>
	<p>
		Recevez nos très cordiales salutations. <br /> L’équipe Zimmer Dental,
	</p>
	<p>
		<em> Pour tout renseignement complémentaire, merci de contacter le
			Service Marketing Z.D. au 01 45 12 35 31 / 35 ou par mail :
			francoise.trupel@zimmer.com </em>
	</p>
	<a href="http://www.journees-zimmerdental.fr"><img
		src="<?php echo $this->logo; ?>"
		alt="Journée Internationale d’Implantologie Zimmer  Dental" /></a>
</body>