<div style="width:940px;">
	<div style="width:500px;padding:20px;text-align:center;margin:0;margin-left:auto;margin-right:auto;margin-top:50px;margin-bottom:50px;border-radius:10px;background:#008FCA;">
		<div style="font-size:2em;font-weight:bold;margin-bottom:10px;">Erreur lors du paiement, merci de réessayer</div>
		<a style="font-size:1.2em;color:white;" href="<?php echo $this->url; ?>">Retour</a>
	</div>
</div>