<form method="<?php echo $this->paybox -> getMethod(); ?>" action="<?php echo $this->paybox -> getAttrib('action'); ?>">
<div id="content-inscription" style="padding-top:50px; background-color:#e3e4e5; width:940px; ">
	<div style="width:740px; margin-left:100px; border-top:0px !important; border:1px solid #C0C0C0; border-bottom: 0px; padding-bottom: 15px;">
		<?php
			if(isset($this->error)){
				?>
				<div class="alert alert-error"><strong><?php echo $this->error; ?></strong></div></span>
				<?php
			}
		?>
		<?php
			if($this->hasError){
				?>
				<div class="alert alert-error">
					<strong>Les champs ci-dessous sont mal renseignés</strong>
					<ul>
					<?php foreach ($this->errorFieldsArray as $value) {
						echo '<li>'.$value.'</li>';
					} ?>
					</ul>
				</div>
				<?php
			}
		?>
		<div class="row" style="margin-left:5px;">
			<div class="span3" style="height:35px; width:150px; background-color:#008bcb;">
				<div class="big-title" style="padding: 10px 10px 10px 10px;">
					Inscription :
				</div>
			</div>
			<div class="span2" style=" margin-left:-10px;">
				<div class="end" style="background-color:#008bcb; height:35px; width:30px;"> </div>
			</div>
		</div>
		<div class="row" style="margin-top:15px; margin-left:5px; padding:10px 0px 10px 0px; border-top:1px ridge; border-bottom:1px ridge;">
			<div class="span6" style="font-weight:bold;">
				INFORMATIONS PERSONNELLES
			</div>
		</div>
		<!-- eventuellement du JS pour slideDown le menu -->
		<div class="row" id="infoinscrip" style="margin-top:15px; margin-left:5px; padding:10px 0px 10px 0px; border-top:1px ridge; border-bottom:1px ridge;">
			
				<table style="width:98%;">
					<tr>
						<td colspan="6">
							<label style="font-weight:bold;color:#008AC2;">Titre : </label>
							<?php echo $this->paybox->gender; ?>
						</td>
					</tr>
					<tr>
						<td colspan="3" style="width:50%;">
							<label style="font-weight:bold;color:#008AC2;">Nom* :</label>
							<?php echo $this->paybox->name; ?>
						</td>
						<td colspan="3" style="width:50%;">
							<label style="font-weight:bold;color:#008AC2;">Prénom* :</label>
							<?php echo $this->paybox->firstname; ?>
						</td>
					</tr>
					<tr>
						<td colspan="6">
							<label style="font-weight:bold;color:#008AC2;">Adresse* :</label>
							<?php echo $this->paybox->address; ?>
						</td>
					</tr>
					<tr>
						<td colspan="2" style="width:33.33%;">
							<label style="font-weight:bold;color:#008AC2;">Code Postal* :</label>
							<?php echo $this->paybox->postalCode; ?>
						</td>
						<td colspan="2" style="width:33.33%;">
							<label style="font-weight:bold;color:#008AC2;">Ville* :</label>
							<?php echo $this->paybox->city; ?>
						</td>
						<td colspan="2" style="width:33.33%;">
							<label style="font-weight:bold;color:#008AC2;">Pays* :</label>
							<?php echo $this->paybox->country; ?>
						</td>
					</tr>
					<tr>
						<td colspan="3" style="width:50%;">
							<label style="font-weight:bold;color:#008AC2;">Téléphone Cabinet :</label>
							<?php echo $this->paybox->officeTelNumber; ?>
						</td>
						<td colspan="3" style="width:50%;">
							<label style="font-weight:bold;color:#008AC2;">Téléphone Portable :</label>
							<?php echo $this->paybox->mobilePhoneNumber; ?>
						</td>
					</tr>
					<tr>
						<td colspan="6">
							<label style="font-weight:bold;color:#008AC2;">E-mail* :</label>
							<?php echo $this->paybox->email; ?>
						</td>
					</tr>
					<tr>
						<td colspan="6">
							<label style="font-weight:bold;color:#008AC2;">Activité :</label>
							<?php echo $this->paybox->activity; ?>
						</td>
					</tr>
					<tr>
						<td colspan="3" style="width:50%;">
							<label style="font-weight:bold;color:#008AC2;">Si vous êtes étudiant, nom de la faculté </label>
							<?php echo $this->paybox->student; ?>
						</td>
						<td colspan="3" style="width:50%;">
							<label style="font-weight:bold;color:#008AC2;">Année suivie </label>
							<?php echo $this->paybox->studentGraduationYear; ?>
						</td>
					</tr>
					<tr>
						<td colspan="6"><?php echo $this->paybox->billingAddress; ?> Merci de cocher cette case si l'adresse de facturation diffère de celle renseignée ci-dessus.</td>
					</tr>
					<tr>
						<td colspan="6" style="padding-top:10px;">
							<span><em>*champ obligatoire</em></span>
						</td>
					</tr>
				</table>
		</div>
		<div class="row" style="margin-left:5px; margin-top:15px;">
			<div class="span3" style="height:35px; width:150px; background-color:#008bcb;">
				<div class="big-title" style="padding: 10px 10px 10px 10px;">
					Règlement : 
				</div>
			</div>
			<div class="span2" style=" margin-left:-10px;">
				<div class="end" style="background-color:#008bcb; height:35px; width:30px;"></div>
			</div>
		</div>
		<div class="row">
			<div class="span7" style="margin-left:65px; margin-top:10px;">
				<table class="radioGroup" style="width:100%;">
					<tr>
						<td style="font-weight:bold; font-size:1.3em;">Tarif unique : 180 Euros</td>
					</tr>
					<tr><td style="font-size: 1.1em;padding-top:10px;"><b>MODALITÉS DE PAIEMENT</b></td></tr>
					<tr><td style="padding-top:10px;"><?php echo $this->paybox->payment; ?></td></tr>
					<tr>
						<td style="padding-top:10px;">
							<?php echo $this->paybox->submit; ?>
							<!-- <input type="submit" style=" float:right; margin-right:30px; background-color:#656565; border:0px; color:#FFFFFF; width:70px; height:20px; font-weight:bold;" />!-->
							<div class="end" style=" float:right; margin-right:-80px; background-color: #656565; width:20px; height:20px;"></div>
						</td>
					</tr>
				</table>

			</div>
		</div>
	</div>

</div>
</form>