<body style="max-width: 640px;">
	<p>Bonjour,</p>

	<p>
		Nous vous remercions pour votre demande d’inscription à la Journée
		Internationale d’Implantologie Zimmer Dental qui aura lieu à Paris le
		jeudi 4 avril 2013. <br /> Dès réception de votre règlement par chèque
		(à l’ordre de Zimmer Dental), vous recevrez une confirmation
		d’inscription ainsi qu’une facture acquittée par courrier. <br /> Dans
		l’attente de vous accueillir prochainement à l’Institut Pasteur,
	</p>
	<p>
		Recevez nos très cordiales salutations. <br /> L’équipe Zimmer Dental,
	</p>
	<p>
		<em> Pour tout renseignement complémentaire, merci de contacter le
			Service Marketing Z.D. au 01 45 12 35 31 / 35 ou par mail :
			francoise.trupel@zimmer.com </em>
	</p>
	<a href="http://www.journees-zimmerdental.fr"><img
		src="<?php echo $this->message->embed(Swift_Image::fromPath(APPLICATION_PATH.'/../public/templates/journees/images/logo_mail.png')); ?>"
		alt="Journée Internationale d’Implantologie Zimmer  Dental" /></a>
</body>